# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Upload TestFlight build"
  lane :beta do
    ensure_git_status_clean
    
    build_number = latest_testflight_build_number(initial_build_number: 0) + 1
    increment_build_number build_number: build_number
    
    match type: "appstore"
    sigh
    gym 
    pilot skip_waiting_for_build_processing: true

    add_git_tag tag: "#{get_version_number}/#{build_number}"
    push_to_git_remote

    reset_git_repo skip_clean: true
  end
end
